import { WORLD_CONFIG } from './world.config'

export const GAME_CONFIG = {
  WIDTH: 3 * WORLD_CONFIG.TILE_SIZE + 2 * WORLD_CONFIG.WORLD_WIDTH,
  HEIGHT: 3 * WORLD_CONFIG.TILE_SIZE + 2 * WORLD_CONFIG.WORLD_HEIGHT,
  NUMBER_OF_AVAILABLE_WORLDS: 5,
  NUMBER_OF_VISIBLE_WORLDS: 4,
}
