const _TILE_SIZE = 8
const _HORIZONTAL_TILES = 12
const _VERTICAL_TILES = 12

export const WORLD_CONFIG = {
  TILE_SIZE: _TILE_SIZE,
  HORIZONTAL_TILES: _HORIZONTAL_TILES,
  VERTICAL_TILES: _VERTICAL_TILES,
  WORLD_WIDTH: _HORIZONTAL_TILES * _TILE_SIZE,
  WORLD_HEIGHT: _VERTICAL_TILES * _TILE_SIZE,
}
